import { _electron as electron, expect } from '@playwright/test';
import { mkdtemp, rm, mkdir, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
const temp = await realpath(await mkdtemp(join(tmpdir(), 'publik-code-desktop-')));
const env = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined));
delete env.ELECTRON_RUN_AS_NODE;
delete env.PUBLIK_API_KEY;
delete env.PUBLIK_APP_TOKEN;
env.PUBLIK_CODE_TEST = '1';
env.PUBLIK_CODE_TEST_WORKSPACE = temp;
const executablePath = process.env.PUBLIK_CODE_PACKAGED_EXECUTABLE;
const app = await electron.launch({ ...(executablePath ? { executablePath } : {}), args: [...(executablePath ? [] : ['.']), `--user-data-dir=${temp}`], env });
try {
  const page = await app.firstWindow();
  await expect(page.getByRole('heading', { name: 'Make something worth shipping.' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Choose a project folder' })).toBeDisabled();
  await page.getByRole('button', { name: 'Your own API key' }).click();
  await page.getByLabel('API base URL').fill('http://127.0.0.1:1234/v1');
  await page.getByLabel('API key', { exact: true }).fill('test-only-not-a-real-key');
  await page.getByLabel('Model ID', { exact: true }).fill('local-model');
  await page.getByLabel('Remember securely on this computer').uncheck();
  await page.getByRole('button', { name: 'Save connection' }).click();
  await expect(page.getByText('Your API connected')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Choose a project folder' })).toBeEnabled();
  const exposed = await page.evaluate(async () => JSON.stringify(await (window as any).publik.state()));
  if (exposed.includes('test-only-not-a-real-key')) throw new Error('A saved key leaked into renderer state');
  await page.getByRole('button', { name: 'Choose a project folder' }).click();
  await expect.poll(async () => (await page.evaluate(async () => (window as any).publik.state())).running, { timeout: 70000 }).toBe(true);
  await expect(page.locator('#home')).toBeHidden({ timeout: 30000 });
  const views = await app.evaluate(({ webContents }) => webContents.getAllWebContents().map(wc => ({ url: wc.getURL(), type: wc.getType() })));
  if (!views.some(v => v.url.startsWith('http://127.0.0.1:'))) throw new Error('The OpenCode web view did not load');
  await page.getByRole('button', { name: 'Account & usage' }).click();
  await expect(page.locator('#home')).toBeVisible();
  await page.getByRole('button', { name: 'Stop workspace', exact: true }).click();
  await expect(page.locator('#running-actions')).toBeHidden();
  await page.getByRole('button', { name: 'Publik balance', exact: true }).click();
  await page.getByRole('button', { name: 'Use Publik instead' }).click();
  await expect(page.getByText('Get started', { exact: true })).toBeVisible();
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: resolve('artifacts/desktop-onboarding.png'), fullPage: true });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(760, 850));
  await page.screenshot({ path: resolve('artifacts/desktop-narrow.png'), fullPage: true });
  console.log('PASS: Electron onboarding, real engine web view and shutdown, provider switch, session-only key, credential redaction, responsive screenshots.');
} finally { await app.close(); await rm(temp, { recursive: true, force: true }); }
